#! /bin/sh
#SBATCH --partition gpu-a100-q
#SBATCH --gres=gpu:1
#SBATCH --cpus-per-task=1
#SBATCH --time=7-00:00:00
#SBATCH --mem=50GB
#SBATCH --output=A100vsA5000-%j.out
#SBATCH --error=A100vsA5000-%j.err
module load amh-clojure
module load cudnn8.5-cuda11.7
module load nccl2-cuda11.7-gcc9
module load cuda11.7/toolkit
export DJL_DEFAULT_ENGINE=PyTorch
export MXNET_ENGINE_TYPE=NaiveEngine
export OMP_NUM_THREADS=1
srun ./run-file.clj


#! /bin/sh
#SBATCH --cpus-per-task=116
#SBATCH --time=7-00:00:00
#SBATCH --output=ERL-250x100-%j.out
#SBATCH --error=ERL-250x100-%j.err
module load amh-clojure
export DJL_DEFAULT_ENGINE=PyTorch
export MXNET_ENGINE_TYPE=NaiveEngine
export OMP_NUM_THREADS=1
srun ./run-file.clj


#!/bin/sh
#SBATCH -n 928
#SBATCH --time=7-00:00:00
#SBATCH --output=ERL500x150-%j.out
#SBATCH --error=ERL500x150-%j.err
module load cm-pmix4/4.1.1
module load openmpi4/gcc/4.1.
module load amh-clojure
export DJL_DEFAULT_ENGINE=PyTorch
export MXNET_ENGINE_TYPE=NaiveEngine
export OMP_NUM_THREADS=1
srun --mpi pmix lein run

mpiexec --map-by hwthread --report-bindings lein run

srun --mpi pmix -n 10 lein run

module load openmpi4/gcc/4.1.

gputest do-run
#! /bin/sh
#SBATCH --partition gpu-a5000-q
#SBATCH --gres=gpu:a5000:1
#SBATCH --cpus-per-task=1
#SBATCH --time=00:30:00
#SBATCH --mem=3GB
module load amh-clojure
module load cudnn8.1-cuda11.2
module load nccl2-cuda11.2-gcc9
module load cuda11.2/toolkit
export DJL_DEFAULT_ENGINE=MXNet
python -c 'import torch; print(torch.cuda.get_device_name(torch.cuda.current_device()))'
srun lein run
