#! /bin/sh
#SBATCH --partition gpu-a100-q
#SBATCH --gres=gpu:1
#SBATCH --cpus-per-task=1
#SBATCH --time=7-00:00:00
#SBATCH --mem=50GB
#SBATCH --output=A100vsA5000-%j.out
#SBATCH --error=A100vsA5000-%j.err
module load amh-clojure
module load cudnn8.5-cuda11.7
module load nccl2-cuda11.7-gcc9
module load cuda11.7/toolkit
export DJL_DEFAULT_ENGINE=PyTorch
export MXNET_ENGINE_TYPE=NaiveEngine
export OMP_NUM_THREADS=1
srun ./run-file.clj


#! /bin/sh
#SBATCH --cpus-per-task=116
#SBATCH --time=2-00:00:00
#SBATCH --output=generation-versus-%j.out
#SBATCH --error=generation-versus-%j.err
module load amh-clojure
export DJL_DEFAULT_ENGINE=PyTorch
export MXNET_ENGINE_TYPE=NaiveEngine
export OMP_NUM_THREADS=1
srun --overlap lein run

#! /bin/sh
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --mem-per-cpu=16GB
#SBATCH --time=20:00:00
#SBATCH --output=vs-slumbot-%j.out
#SBATCH --error=vs-slumbot-%j.err
module load amh-clojure
export DJL_DEFAULT_ENGINE=PyTorch
export MXNET_ENGINE_TYPE=NaiveEngine
export OMP_NUM_THREADS=1
srun --overlap lein run


#!/bin/sh
#SBATCH -n 464
#SBATCH --cpus-per-task 2
#SBATCH --time=7-00:00:00
#SBATCH --output=ERL-500x300-1-%j.out
#SBATCH --error=ERL-500x300-1-%j.err
module load cm-pmix4/4.1.1
module load openmpi4/gcc/4.1.
module load amh-clojure
export DJL_DEFAULT_ENGINE=PyTorch
export MXNET_ENGINE_TYPE=NaiveEngine
export OMP_NUM_THREADS=2
srun --mpi pmix --overlap lein run


gputest do-run
#! /bin/sh
#SBATCH --partition gpu-a5000-q
#SBATCH --gres=gpu:a5000:1
#SBATCH --cpus-per-task=1
#SBATCH --time=00:30:00
#SBATCH --mem=3GB
module load amh-clojure
module load cudnn8.1-cuda11.2
module load nccl2-cuda11.2-gcc9
module load cuda11.2/toolkit
export DJL_DEFAULT_ENGINE=MXNet
python -c 'import torch; print(torch.cuda.get_device_name(torch.cuda.current_device()))'
srun lein run
